# Generated by Django 2.1.7 on 2019-03-28 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20190328_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingprocess',
            name='custom_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
