# Generated by Django 2.1.7 on 2019-03-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20190328_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingprocess',
            name='website_lists',
            field=models.TextField(),
        ),
    ]
