# Generated by Django 2.1.7 on 2019-03-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20190329_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingprocess',
            name='custom_user',
        ),
    ]
